name: UI Autotests
on:
  push:
    branches: [ MPGY ]
  pull_request:
    branches: [ MPGY ]
  workflow_dispatch:      # ОБЯЗАТЕЛЬНО: эта строка разрешает запуск через API и бота
    inputs:
      test_file:
        description: 'Forms/dszn136200.py'
        required: true
        default: 'test1/' # Папка по умолчанию, если ничего не введено

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb
      - name: Run tests
        run: xvfb-run pytest ${{ github.event.inputs.test_file }}  # Или ваша команда запуска
      - name: Send Telegram Notification
        if: always()
        env:
          # Проверьте эти два имени в настройках GitHub!
          TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -v -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
          -d "chat_id=${CHAT_ID}&text=📊 Тесты окончены!"