name: UI Autotests
on:
  push:
    branches: [ MPGY ]
  pull_request:
    branches: [ MPGY ]
  workflow_dispatch:      # ОБЯЗАТЕЛЬНО: эта строка разрешает запуск через API и бота
    inputs:
      test_file: # Название параметра
        description: 'Forms/dszn136200.py'
        required: true
        default: 'tests/'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps
      - name: Run specific test
        # Используем переменную из ввода в команде запуска
        run: pytest ${{ github.event.inputs.test_file }}
      - name: Run tests
        run: python -m pytest --alluredir allure-results Forms/dszn136200.py  # Или ваша команда запуска
      - name: Send Telegram Notification
        if: always() # Выполнять даже если тесты упали
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.8360653159:AAEtsQkTW6FOS-F7T2pBPlOXVpUmHXaVk8A}}/sendMessage" \
          -d "chat_id=${{ secrets.8360653159}}&text=📊 Тесты завершены! Проверь отчет в GitHub Actions."